import { execFile } from 'node:child_process';
import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { promisify } from 'node:util';
import { readReleaseVersion } from './verify-release-version.mjs';

const root = path.resolve(process.cwd());
const execFileAsync = promisify(execFile);
const ignoredDirectories = new Set([
  '.git',
  'node_modules',
  'dist',
  'storybook-static',
  'target',
  'vault',
  '.obsidian',
  'coverage',
  'test-results',
  'screenshots',
  'design-qa',
  'runtime',
  'logs',
  'checkpoints',
  'backups',
  'cache',
  'release',
  'installers',
  'artifacts',
]);
const forbiddenRepositorySegments = new Set([
  'desktop',
  'node_modules',
  'dist',
  'storybook-static',
  'target',
  'vault',
  '.obsidian',
  'coverage',
  'test-results',
  'screenshots',
  'design-qa',
  'release',
  'installers',
  'artifacts',
]);
const binaryExtensions = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.ico', '.icns', '.pdf',
  '.zip', '.dmg', '.app', '.exe', '.msi', '.dll', '.dylib', '.so', '.a', '.rlib',
  '.wasm', '.woff', '.woff2', '.ttf', '.otf',
]);
const requiredFiles = [
  'README.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
  'CHANGELOG.md',
  'LICENSE',
  'NOTICE',
  '.gitattributes',
  'package.json',
  'package-lock.json',
  'desktop-ui/index.html',
  'desktop-ui/app.js',
  'desktop-ui/styles.css',
  'src-tauri/Cargo.toml',
  'src-tauri/Cargo.lock',
  'src-tauri/tauri.conf.json',
  'src-tauri/src/lib.rs',
  'src-tauri/src/assistant_runtime.rs',
  'src-tauri/src/command_bus.rs',
  'src-tauri/src/execution_ticket.rs',
  'src-tauri/src/memory.rs',
  'src-tauri/src/policy.rs',
  'src-tauri/src/task_runtime.rs',
  'src-tauri/src/obsidian.rs',
  'src-tauri/src/obsidian_management.rs',
  'src-tauri/src/runtime_db.rs',
  'src-tauri/src/skill_lifecycle.rs',
  'src-tauri/src/trace.rs',
  'src-tauri/src/vault_batch.rs',
  'docs/MEMORY_V2.md',
  'docs/RELEASING.md',
  'docs/assets/architecture-overview.svg',
  'docs/schemas/memory-record.schema.json',
  'docs/schemas/memory-reflection-job.schema.json',
  '.github/ISSUE_TEMPLATE/bug_report.yml',
  '.github/ISSUE_TEMPLATE/feature_request.yml',
  '.github/workflows/ci.yml',
  '.github/workflows/release.yml',
  '.github/workflows/windows-installer.yml',
  'scripts/build-macos-python-runtime.mjs',
  'scripts/build-macos-native.mjs',
  'scripts/run-native-quality.mjs',
  'scripts/generate-third-party-notices.mjs',
  'scripts/sign-windows.ps1',
  'scripts/verify-release-artifact.mjs',
  'scripts/verify-release-version.mjs',
  'scripts/verify-macos-helpers.mjs',
  'src-tauri/tauri.macos.conf.json',
  'src-tauri/tauri.release.conf.json',
  'skills/deep-research/SKILL.md',
  'skills/deep-research/input.schema.json',
  'skills/deep-research/output.schema.json',
  'skills/deep-research/manifest.json',
  'skills/deep-research/origin.json',
  'skills/deep-research/scripts/validate-research-result.mjs',
];
const bilingualDocuments = [
  'README.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
  'CHANGELOG.md',
  'docs/AI_ASSISTANT_INSTRUCTIONS.md',
  'docs/BRAND_GUIDE.md',
  'docs/PRODUCT_REQUIREMENTS.md',
  'docs/RELEASING.md',
  'docs/schemas/README.md',
];
const canonicalRootDocuments = new Set([
  'README.md',
  'CHANGELOG.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
]);
const canonicalDirectDocs = new Set([
  'AI_ASSISTANT_INSTRUCTIONS.md',
  'BRAND_GUIDE.md',
  'MEMORY_V2.md',
  'PRODUCT_REQUIREMENTS.md',
  'RELEASING.md',
]);
const canonicalDocumentation = [
  ...canonicalRootDocuments,
  ...[...canonicalDirectDocs].map((fileName) => `docs/${fileName}`),
  'docs/schemas/README.md',
];
const obsoleteDocumentation = [
  'docs/HERMES_FUSION_STATUS.md',
  'docs/P0_P2_COMPLETION_MATRIX.md',
  'docs/V02_IMPLEMENTATION_STATUS.md',
  'docs/V03_CREATION_STUDIO_STATUS.md',
  'docs/V03_REPORTS_STATUS.md',
  'docs/YUNSPIRE_DEVELOPMENT_PLAYBOOK.md',
];
const generatedAttributionPattern = new RegExp(
  `(?:generated by|co-authored-by:).*(?:${['Chat', 'GPT'].join('')}|${['Co', 'dex'].join('')}|${['Clau', 'de'].join('')})`,
  'gi',
);
const forbiddenTestSourcePattern = /(?:^|\/)(?:tests?\/|[^/]+\.(?:test|spec)\.(?:mjs|js|jsx|ts|tsx))$/iu;
const forbiddenRustTestPattern = /#\[(?:test|cfg\([^\]]*\btest\b[^\]]*)\)\]/u;
const forbiddenPatterns = [
  { label: 'macOS absolute user path', pattern: /\/Users\/[^/\s"'`<>]+\//g },
  { label: 'Linux absolute user path', pattern: /\/home\/[^/\s"'`<>]+\//g },
  { label: 'Windows absolute user path', pattern: /[A-Za-z]:\\Users\\[^\\\s"'`<>]+\\/g },
  { label: 'local file URL', pattern: /file:\/\/(?:\/|[A-Za-z]:)/g },
  { label: 'private key', pattern: /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/g },
  { label: 'AWS access key', pattern: /\bAKIA[0-9A-Z]{16}\b/g },
  { label: 'OpenAI-style secret', pattern: /\bsk-[A-Za-z0-9_-]{20,}\b/g },
  { label: 'generated authorship marker', pattern: generatedAttributionPattern },
];

async function exists(relativePath) {
  try {
    await stat(path.join(root, relativePath));
    return true;
  } catch {
    return false;
  }
}

async function collectFiles(directory, relative = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const nextRelative = path.join(relative, entry.name);
    if (entry.isDirectory()) {
      if (ignoredDirectories.has(entry.name) || entry.name.endsWith('.app')) continue;
      files.push(...await collectFiles(path.join(directory, entry.name), nextRelative));
    } else if (entry.isFile()) {
      files.push(nextRelative);
    }
  }
  return files;
}

const failures = [];
for (const required of requiredFiles) {
  if (!await exists(required)) failures.push(`missing required file: ${required}`);
}
for (const document of canonicalDocumentation) {
  if (!await exists(document)) failures.push(`missing canonical documentation: ${document}`);
}
for (const document of obsoleteDocumentation) {
  if (await exists(document)) failures.push(`obsolete documentation must be deleted: ${document}`);
}

const rootEntries = await readdir(root, { withFileTypes: true });
for (const entry of rootEntries) {
  if (entry.isFile() && entry.name.endsWith('.md') && !canonicalRootDocuments.has(entry.name)) {
    failures.push(`unregistered root documentation: ${entry.name}`);
  }
}
const docsEntries = await readdir(path.join(root, 'docs'), { withFileTypes: true });
for (const entry of docsEntries) {
  if (entry.isFile() && entry.name.endsWith('.md') && !canonicalDirectDocs.has(entry.name)) {
    failures.push(`unregistered direct documentation: docs/${entry.name}`);
  }
}

for (const document of bilingualDocuments) {
  if (!await exists(document)) continue;
  const text = await readFile(path.join(root, document), 'utf8');
  if (!/^## 中文$/m.test(text) || !/^## English$/m.test(text)) {
    failures.push(`bilingual headings missing: ${document}`);
  }
}

if (await exists('.github/workflows/release.yml')) {
  const releaseWorkflow = await readFile(path.join(root, '.github/workflows/release.yml'), 'utf8');
  const requiredReleaseGates = [
    ['release/v* branch trigger', /release\/v\*/u],
    ['source identity gate', /verify-release-version\.mjs\s+source/u],
    ['clean committed source requirement', /--require-clean\s+true/u],
    ['manifest convergence gate', /verify-release-version\.mjs\s+manifests/u],
    ['pre-creation tag and release absence gate', /verify-release-version\.mjs\s+prepare/u],
    ['draft release identity gate', /verify-release-version\.mjs\s+prepublish/u],
    ['prepublish run provenance binding', /--run-provenance\s+"\$RUN_PROVENANCE"/u],
    [
      'final draft revalidation immediately before publication',
      /Publish the verified Release as Latest[\s\S]*verify-release-version\.mjs\s+prepublish[\s\S]*gh release edit/u,
    ],
    ['attempt-scoped build artifacts', /attempt-\$\{\{\s*github\.run_attempt\s*\}\}/u],
    ['run-provenance cleanup ownership', /RUN_PROVENANCE:\s*yunspire-release-run:/u],
    ['annotated-tag cleanup ownership', /tag_message[\s\S]*RUN_PROVENANCE/u],
    ['existing-tag verification', /--verify-tag/u],
    ['explicit latest release selection', /--latest(?:\s|$)/mu],
  ];
  for (const [label, pattern] of requiredReleaseGates) {
    if (!pattern.test(releaseWorkflow)) failures.push(`release workflow is missing ${label}`);
  }
  if (/--clobber/u.test(releaseWorkflow)) {
    failures.push('release workflow must never overwrite an existing release asset with --clobber');
  }
  if (/gh release delete[^\n]*--cleanup-tag/u.test(releaseWorkflow)) {
    failures.push('release cleanup must verify and delete its owned annotated tag separately');
  }
  if (/workflow_dispatch\s*:/u.test(releaseWorkflow)) {
    failures.push('release workflow must only publish from the version-bound release/v* branch trigger');
  }
  const noSignCount = releaseWorkflow.match(/--no-sign/gu)?.length || 0;
  const unsignedManifestCount = releaseWorkflow.match(/--signed\s+false/gu)?.length || 0;
  const prepublishProvenanceCount = releaseWorkflow.match(/--run-provenance\s+"\$RUN_PROVENANCE"/gu)?.length || 0;
  if (noSignCount !== 2 || unsignedManifestCount !== 2) {
    failures.push(`release workflow must build exactly two explicitly unsigned installers; no-sign=${noSignCount} manifests=${unsignedManifestCount}`);
  }
  if (/--require-signed\s+true/u.test(releaseWorkflow)) {
    failures.push('unsigned release workflow must not require signed artifacts');
  }
  if (prepublishProvenanceCount !== 2) {
    failures.push(`release workflow must bind both prepublish gates to this run provenance; found=${prepublishProvenanceCount}`);
  }
}

if (await exists('scripts/verify-release-version.mjs')) {
  const releaseVerifier = await readFile(path.join(root, 'scripts/verify-release-version.mjs'), 'utf8');
  const prepublishStart = releaseVerifier.indexOf('export async function verifyPrepublish');
  const prepublishEnd = releaseVerifier.indexOf('function manifestSourceCommit', prepublishStart);
  const prepublishVerifier = prepublishStart >= 0 && prepublishEnd > prepublishStart
    ? releaseVerifier.slice(prepublishStart, prepublishEnd)
    : '';
  if (!/remoteBranchCommit\(repository, 'main'\)/u.test(prepublishVerifier)) {
    failures.push('prepublish verification must require the built commit to remain the remote main HEAD');
  }
  if (!/remoteAnnotatedTag\(repository, identity\.tag\)/u.test(prepublishVerifier)
      || !/release\.body[\s\S]*provenance/u.test(prepublishVerifier)) {
    failures.push('prepublish verification must bind the annotated tag and draft Release body to this workflow run');
  }
  const stableReleaseGuards = releaseVerifier.match(/stable release workflow does not accept prerelease version/gu)?.length || 0;
  if (stableReleaseGuards < 2) {
    failures.push('prepare and prepublish verification must reject prerelease versions from the stable Latest workflow');
  }
}

if (await exists('scripts/verify-release-artifact.mjs')) {
  const artifactVerifier = await readFile(path.join(root, 'scripts/verify-release-artifact.mjs'), 'utf8');
  if (!/requireClean:\s*option\('require-clean',\s*\{\s*fallback:\s*'true'\s*\}\)\s*===\s*'true'/u.test(artifactVerifier)) {
    failures.push('release artifact manifests must default to a clean checked-out source tree');
  }
}

if (await exists('.github/workflows/windows-installer.yml')) {
  const windowsInstallerWorkflow = await readFile(
    path.join(root, '.github/workflows/windows-installer.yml'),
    'utf8',
  );
  const requiredWindowsCiGates = [
    ['CI-only workflow label', /CI (?:verification|only)/iu],
    ['shared release installer configuration', /--config\s+src-tauri\/tauri\.release\.conf\.json/u],
    ['explicit unsigned build flag', /--no-sign/u],
    ['silent install and startup smoke', /sign-windows\.ps1[\s\S]*VerifyUnsignedInstaller/u],
  ];
  for (const [label, pattern] of requiredWindowsCiGates) {
    if (!pattern.test(windowsInstallerWorkflow)) failures.push(`Windows installer CI is missing ${label}`);
  }
  if (/actions\/upload-artifact@/u.test(windowsInstallerWorkflow)) {
    failures.push('Windows installer CI must not upload a second distributable installer');
  }
}

if (await exists('src-tauri/tauri.release.conf.json')) {
  try {
    const fragments = await Promise.all([
      'src-tauri/tauri.conf.json',
      'src-tauri/tauri.windows.conf.json',
      'src-tauri/tauri.release.conf.json',
    ].map((relativePath) => readFile(path.join(root, relativePath), 'utf8').then(JSON.parse)));
    const mergeConfig = (base, overlay) => {
      if (!overlay || typeof overlay !== 'object' || Array.isArray(overlay)) return overlay;
      const merged = { ...base };
      for (const [key, value] of Object.entries(overlay)) {
        merged[key] = value && typeof value === 'object' && !Array.isArray(value)
          ? mergeConfig(merged[key] || {}, value)
          : value;
      }
      return merged;
    };
    const releaseConfig = fragments.reduce(mergeConfig, {});
    const bundle = releaseConfig.bundle || {};
    const windows = bundle.windows || {};
    const nsis = windows.nsis || {};
    const languages = Array.isArray(nsis.languages) ? nsis.languages : [];
    if (bundle.licenseFile !== null) {
      failures.push('Windows release installer must not add a separate license page');
    }
    if (windows.allowDowngrades !== false) {
      failures.push('Windows release installer must block downgrades');
    }
    if (windows.webviewInstallMode?.type !== 'offlineInstaller'
      || windows.webviewInstallMode?.silent !== true) {
      failures.push('Windows release installer must embed the complete WebView2 offline installer silently');
    }
    if (windows.signCommand != null) {
      failures.push('unsigned Windows release must not configure a signing command');
    }
    if (nsis.installMode !== 'currentUser') {
      failures.push('Windows NSIS release must use currentUser install mode');
    }
    if (nsis.displayLanguageSelector !== false) {
      failures.push('Windows NSIS release must disable the language selector');
    }
    if (languages.length !== 2 || languages[0] !== 'SimpChinese' || languages[1] !== 'English') {
      failures.push('Windows NSIS languages must be SimpChinese then English');
    }
    for (const property of ['template', 'installerHooks', 'startMenuFolder']) {
      if (nsis[property] != null) {
        failures.push(`Windows NSIS ${property} must remain unset to avoid custom or unnecessary pages`);
      }
    }
  } catch (error) {
    failures.push(`effective Windows release installer configuration is invalid: ${error.message}`);
  }
}

const files = await collectFiles(root);
for (const relativePath of files) {
  const segments = relativePath.split(path.sep);
  if (forbiddenTestSourcePattern.test(relativePath)) {
    failures.push(`test source must be deleted from the release tree: ${relativePath}`);
    continue;
  }
  if (segments.some((segment) => segment === '.DS_Store' || segment === '__pycache__' || segment.endsWith('.pyc'))) {
    failures.push(`local cache artifact present: ${relativePath}`);
    continue;
  }
  if (segments.some((segment) => forbiddenRepositorySegments.has(segment))) {
    failures.push(`generated or local artifact present: ${relativePath}`);
    continue;
  }
  if (binaryExtensions.has(path.extname(relativePath).toLowerCase())) continue;
  const fileStat = await stat(path.join(root, relativePath));
  if (fileStat.size > 5 * 1024 * 1024) continue;
  const text = await readFile(path.join(root, relativePath), 'utf8');
  if (relativePath.endsWith('.rs') && forbiddenRustTestPattern.test(text)) {
    failures.push(`Rust test code must be deleted from the release tree: ${relativePath}`);
  }
  if (relativePath.startsWith(`.github${path.sep}workflows${path.sep}`)
      && /\.ya?ml$/i.test(relativePath)) {
    for (const line of text.split(/\r?\n/)) {
      const action = line.match(/^\s*uses:\s*([^\s#]+)/)?.[1];
      if (action && !action.startsWith('./') && !/@[0-9a-f]{40}$/i.test(action)) {
        failures.push(`GitHub Action is not pinned to a commit SHA: ${relativePath} -> ${action}`);
      }
    }
  }
  for (const { label, pattern } of forbiddenPatterns) {
    pattern.lastIndex = 0;
    if (pattern.test(text)) failures.push(`${label}: ${relativePath}`);
  }
}

try {
  const { stdout } = await execFileAsync('git', ['ls-files', '-z'], {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 10 * 1024 * 1024,
  });
  const trackedFiles = new Set(stdout.split('\0').filter(Boolean));
  for (const required of requiredFiles) {
    if (!trackedFiles.has(required)) failures.push(`required release file is not tracked in the Git index: ${required}`);
  }
  for (const relativePath of trackedFiles) {
    const segments = relativePath.split('/');
    const extension = path.extname(relativePath).toLowerCase();
    if (segments.some((segment) => forbiddenRepositorySegments.has(segment) || segment.endsWith('.app'))) {
      failures.push(`generated or local artifact is tracked: ${relativePath}`);
    } else if (['.app', '.dmg', '.exe', '.msi', '.sig', '.sha256', '.zip'].includes(extension)) {
      failures.push(`installer or release output is tracked: ${relativePath}`);
    }
  }
} catch (error) {
  failures.push(`unable to inspect the Git index: ${error.message}`);
}

const packageJson = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const packageVersion = packageJson.version;
try {
  await readReleaseVersion(root);
} catch (error) {
  failures.push(`release version validation failed: ${error.message}`);
}
const packageLock = JSON.parse(await readFile(path.join(root, 'package-lock.json'), 'utf8'));
if (packageLock.version !== packageVersion || packageLock.packages?.['']?.version !== packageVersion) {
  failures.push(`version mismatch in package-lock.json; expected ${packageVersion}`);
}
const versionChecks = [
  ['src-tauri/tauri.conf.json', new RegExp(`"version"\\s*:\\s*"${packageVersion.replaceAll('.', '\\.')}"`)],
  ['src-tauri/Cargo.toml', new RegExp(`^version\\s*=\\s*"${packageVersion.replaceAll('.', '\\.')}"`, 'm')],
  ['desktop-ui/index.html', new RegExp(`版本 ${packageVersion.replaceAll('.', '\\.')}`)],
  ['desktop-ui/app.js', new RegExp(`Yunspire Desktop ${packageVersion.replaceAll('.', '\\.')}`)],
  ['skills/video-content-analysis/scripts/yunspire_speech_info.plist', new RegExp(`<string>${packageVersion.replaceAll('.', '\\.')}<\\/string>`)],
  ['CHANGELOG.md', new RegExp(`^### ${packageVersion.replaceAll('.', '\\.')} (?:-|$)`, 'm')],
  ['README.md', new RegExp('当前版本为 `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['SECURITY.md', new RegExp('当前版本为 `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/AI_ASSISTANT_INSTRUCTIONS.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/BRAND_GUIDE.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/PRODUCT_REQUIREMENTS.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/schemas/README.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/assets/architecture-overview.svg', new RegExp(`v${packageVersion.replaceAll('.', '\\.')}`)],
];
for (const [relativePath, pattern] of versionChecks) {
  const text = await readFile(path.join(root, relativePath), 'utf8');
  if (!pattern.test(text)) failures.push(`version mismatch in ${relativePath}; expected ${packageVersion}`);
}

const positioningChecks = [
  ['package.json', /本地自成长个人知识中枢/u],
  ['src-tauri/Cargo.toml', /local-first self-growing personal knowledge hub/u],
  ['desktop-ui/index.html', /云枢 Yunspire · 自成长知识中枢/u],
  ['desktop-ui/index.html', /面向个人、本地优先的自成长知识中枢/u],
];
for (const [relativePath, pattern] of positioningChecks) {
  const text = await readFile(path.join(root, relativePath), 'utf8');
  if (!pattern.test(text)) failures.push(`current product positioning missing from ${relativePath}`);
}

if (failures.length) {
  console.error('RELEASE_AUDIT_FAILED');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log(`RELEASE_AUDIT_OK ${files.length} files version=${packageVersion}`);
