import { execFile } from 'node:child_process';
import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { promisify } from 'node:util';

const root = path.resolve(process.cwd());
const execFileAsync = promisify(execFile);
const ignoredDirectories = new Set([
  '.git',
  'node_modules',
  'dist',
  'storybook-static',
  'target',
  'vault',
  '.obsidian',
  'coverage',
  'test-results',
  'screenshots',
  'design-qa',
  'runtime',
  'logs',
  'checkpoints',
  'backups',
  'cache',
  'release',
  'installers',
  'artifacts',
]);
const forbiddenRepositorySegments = new Set([
  'desktop',
  'node_modules',
  'dist',
  'storybook-static',
  'target',
  'vault',
  '.obsidian',
  'coverage',
  'test-results',
  'screenshots',
  'design-qa',
  'release',
  'installers',
  'artifacts',
]);
const binaryExtensions = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.ico', '.icns', '.pdf',
  '.zip', '.dmg', '.app', '.exe', '.msi', '.dll', '.dylib', '.so', '.a', '.rlib',
  '.wasm', '.woff', '.woff2', '.ttf', '.otf',
]);
const requiredFiles = [
  'README.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
  'CHANGELOG.md',
  'LICENSE',
  'NOTICE',
  '.gitattributes',
  'package.json',
  'package-lock.json',
  'desktop-ui/index.html',
  'desktop-ui/app.js',
  'desktop-ui/styles.css',
  'src-tauri/Cargo.toml',
  'src-tauri/Cargo.lock',
  'src-tauri/tauri.conf.json',
  'src-tauri/src/lib.rs',
  'src-tauri/src/assistant_runtime.rs',
  'src-tauri/src/command_bus.rs',
  'src-tauri/src/execution_ticket.rs',
  'src-tauri/src/memory.rs',
  'src-tauri/src/policy.rs',
  'src-tauri/src/task_runtime.rs',
  'src-tauri/src/obsidian.rs',
  'src-tauri/src/obsidian_management.rs',
  'src-tauri/src/runtime_db.rs',
  'src-tauri/src/skill_lifecycle.rs',
  'src-tauri/src/trace.rs',
  'src-tauri/src/vault_batch.rs',
  'docs/MEMORY_V2.md',
  'docs/assets/architecture-overview.svg',
  'docs/schemas/memory-record.schema.json',
  'docs/schemas/memory-reflection-job.schema.json',
  '.github/ISSUE_TEMPLATE/bug_report.yml',
  '.github/ISSUE_TEMPLATE/feature_request.yml',
  '.github/workflows/ci.yml',
  '.github/workflows/windows-installer.yml',
  'scripts/generate-third-party-notices.mjs',
  'scripts/verify-release-artifact.mjs',
  'skills/deep-research/SKILL.md',
  'skills/deep-research/input.schema.json',
  'skills/deep-research/output.schema.json',
  'skills/deep-research/manifest.json',
  'skills/deep-research/origin.json',
  'skills/deep-research/scripts/validate-research-result.mjs',
];
const bilingualDocuments = [
  'README.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
  'CHANGELOG.md',
  'docs/AI_ASSISTANT_INSTRUCTIONS.md',
  'docs/BRAND_GUIDE.md',
  'docs/PRODUCT_REQUIREMENTS.md',
  'docs/schemas/README.md',
];
const canonicalRootDocuments = new Set([
  'README.md',
  'CHANGELOG.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
]);
const canonicalDirectDocs = new Set([
  'AI_ASSISTANT_INSTRUCTIONS.md',
  'BRAND_GUIDE.md',
  'MEMORY_V2.md',
  'PRODUCT_REQUIREMENTS.md',
]);
const canonicalDocumentation = [
  ...canonicalRootDocuments,
  ...[...canonicalDirectDocs].map((fileName) => `docs/${fileName}`),
  'docs/schemas/README.md',
];
const obsoleteDocumentation = [
  'docs/HERMES_FUSION_STATUS.md',
  'docs/P0_P2_COMPLETION_MATRIX.md',
  'docs/V02_IMPLEMENTATION_STATUS.md',
  'docs/V03_CREATION_STUDIO_STATUS.md',
  'docs/V03_REPORTS_STATUS.md',
  'docs/YUNSPIRE_DEVELOPMENT_PLAYBOOK.md',
];
const generatedAttributionPattern = new RegExp(
  `(?:generated by|co-authored-by:).*(?:${['Chat', 'GPT'].join('')}|${['Co', 'dex'].join('')}|${['Clau', 'de'].join('')})`,
  'gi',
);
const forbiddenTestSourcePattern = /(?:^|\/)(?:tests?\/|[^/]+\.(?:test|spec)\.(?:mjs|js|jsx|ts|tsx))$/iu;
const forbiddenRustTestPattern = /#\[(?:test|cfg\([^\]]*\btest\b[^\]]*)\)\]/u;
const forbiddenPatterns = [
  { label: 'macOS absolute user path', pattern: /\/Users\/[^/\s"'`<>]+\//g },
  { label: 'Linux absolute user path', pattern: /\/home\/[^/\s"'`<>]+\//g },
  { label: 'Windows absolute user path', pattern: /[A-Za-z]:\\Users\\[^\\\s"'`<>]+\\/g },
  { label: 'local file URL', pattern: /file:\/\/(?:\/|[A-Za-z]:)/g },
  { label: 'private key', pattern: /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/g },
  { label: 'AWS access key', pattern: /\bAKIA[0-9A-Z]{16}\b/g },
  { label: 'OpenAI-style secret', pattern: /\bsk-[A-Za-z0-9_-]{20,}\b/g },
  { label: 'generated authorship marker', pattern: generatedAttributionPattern },
];

async function exists(relativePath) {
  try {
    await stat(path.join(root, relativePath));
    return true;
  } catch {
    return false;
  }
}

async function collectFiles(directory, relative = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const nextRelative = path.join(relative, entry.name);
    if (entry.isDirectory()) {
      if (ignoredDirectories.has(entry.name) || entry.name.endsWith('.app')) continue;
      files.push(...await collectFiles(path.join(directory, entry.name), nextRelative));
    } else if (entry.isFile()) {
      files.push(nextRelative);
    }
  }
  return files;
}

const failures = [];
for (const required of requiredFiles) {
  if (!await exists(required)) failures.push(`missing required file: ${required}`);
}
for (const document of canonicalDocumentation) {
  if (!await exists(document)) failures.push(`missing canonical documentation: ${document}`);
}
for (const document of obsoleteDocumentation) {
  if (await exists(document)) failures.push(`obsolete documentation must be deleted: ${document}`);
}

const rootEntries = await readdir(root, { withFileTypes: true });
for (const entry of rootEntries) {
  if (entry.isFile() && entry.name.endsWith('.md') && !canonicalRootDocuments.has(entry.name)) {
    failures.push(`unregistered root documentation: ${entry.name}`);
  }
}
const docsEntries = await readdir(path.join(root, 'docs'), { withFileTypes: true });
for (const entry of docsEntries) {
  if (entry.isFile() && entry.name.endsWith('.md') && !canonicalDirectDocs.has(entry.name)) {
    failures.push(`unregistered direct documentation: docs/${entry.name}`);
  }
}

for (const document of bilingualDocuments) {
  if (!await exists(document)) continue;
  const text = await readFile(path.join(root, document), 'utf8');
  if (!/^## 中文$/m.test(text) || !/^## English$/m.test(text)) {
    failures.push(`bilingual headings missing: ${document}`);
  }
}

const files = await collectFiles(root);
for (const relativePath of files) {
  const segments = relativePath.split(path.sep);
  if (forbiddenTestSourcePattern.test(relativePath)) {
    failures.push(`test source must be deleted from the release tree: ${relativePath}`);
    continue;
  }
  if (segments.some((segment) => segment === '.DS_Store' || segment === '__pycache__' || segment.endsWith('.pyc'))) {
    failures.push(`local cache artifact present: ${relativePath}`);
    continue;
  }
  if (segments.some((segment) => forbiddenRepositorySegments.has(segment))) {
    failures.push(`generated or local artifact present: ${relativePath}`);
    continue;
  }
  if (binaryExtensions.has(path.extname(relativePath).toLowerCase())) continue;
  const fileStat = await stat(path.join(root, relativePath));
  if (fileStat.size > 5 * 1024 * 1024) continue;
  const text = await readFile(path.join(root, relativePath), 'utf8');
  if (relativePath.endsWith('.rs') && forbiddenRustTestPattern.test(text)) {
    failures.push(`Rust test code must be deleted from the release tree: ${relativePath}`);
  }
  if (relativePath.startsWith(`.github${path.sep}workflows${path.sep}`)
      && /\.ya?ml$/i.test(relativePath)) {
    for (const line of text.split(/\r?\n/)) {
      const action = line.match(/^\s*uses:\s*([^\s#]+)/)?.[1];
      if (action && !action.startsWith('./') && !/@[0-9a-f]{40}$/i.test(action)) {
        failures.push(`GitHub Action is not pinned to a commit SHA: ${relativePath} -> ${action}`);
      }
    }
  }
  for (const { label, pattern } of forbiddenPatterns) {
    pattern.lastIndex = 0;
    if (pattern.test(text)) failures.push(`${label}: ${relativePath}`);
  }
}

try {
  const { stdout } = await execFileAsync('git', ['ls-files', '-z'], {
    cwd: root,
    encoding: 'utf8',
    maxBuffer: 10 * 1024 * 1024,
  });
  const trackedFiles = new Set(stdout.split('\0').filter(Boolean));
  for (const required of requiredFiles) {
    if (!trackedFiles.has(required)) failures.push(`required release file is not tracked in the Git index: ${required}`);
  }
  for (const relativePath of trackedFiles) {
    const segments = relativePath.split('/');
    const extension = path.extname(relativePath).toLowerCase();
    if (segments.some((segment) => forbiddenRepositorySegments.has(segment) || segment.endsWith('.app'))) {
      failures.push(`generated or local artifact is tracked: ${relativePath}`);
    } else if (['.app', '.dmg', '.exe', '.msi', '.sig', '.sha256', '.zip'].includes(extension)) {
      failures.push(`installer or release output is tracked: ${relativePath}`);
    }
  }
} catch (error) {
  failures.push(`unable to inspect the Git index: ${error.message}`);
}

const packageJson = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const packageVersion = packageJson.version;
const packageLock = JSON.parse(await readFile(path.join(root, 'package-lock.json'), 'utf8'));
if (packageLock.version !== packageVersion || packageLock.packages?.['']?.version !== packageVersion) {
  failures.push(`version mismatch in package-lock.json; expected ${packageVersion}`);
}
const versionChecks = [
  ['src-tauri/tauri.conf.json', new RegExp(`"version"\\s*:\\s*"${packageVersion.replaceAll('.', '\\.')}"`)],
  ['src-tauri/Cargo.toml', new RegExp(`^version\\s*=\\s*"${packageVersion.replaceAll('.', '\\.')}"`, 'm')],
  ['desktop-ui/index.html', new RegExp(`版本 ${packageVersion.replaceAll('.', '\\.')}`)],
  ['desktop-ui/app.js', new RegExp(`Yunspire Desktop ${packageVersion.replaceAll('.', '\\.')}`)],
  ['skills/video-content-analysis/scripts/yunspire_speech_info.plist', new RegExp(`<string>${packageVersion.replaceAll('.', '\\.')}<\\/string>`)],
  ['CHANGELOG.md', new RegExp(`^### ${packageVersion.replaceAll('.', '\\.')} (?:-|$)`, 'm')],
  ['README.md', new RegExp('当前版本为 `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['SECURITY.md', new RegExp('当前版本为 `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/AI_ASSISTANT_INSTRUCTIONS.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/BRAND_GUIDE.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/PRODUCT_REQUIREMENTS.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/schemas/README.md', new RegExp('Current version: `' + packageVersion.replaceAll('.', '\\.') + '`')],
  ['docs/assets/architecture-overview.svg', new RegExp(`v${packageVersion.replaceAll('.', '\\.')}`)],
];
for (const [relativePath, pattern] of versionChecks) {
  const text = await readFile(path.join(root, relativePath), 'utf8');
  if (!pattern.test(text)) failures.push(`version mismatch in ${relativePath}; expected ${packageVersion}`);
}

const positioningChecks = [
  ['package.json', /本地自成长个人知识中枢/u],
  ['src-tauri/Cargo.toml', /local-first self-growing personal knowledge hub/u],
  ['desktop-ui/index.html', /云枢 Yunspire · 自成长知识中枢/u],
  ['desktop-ui/index.html', /面向个人、本地优先的自成长知识中枢/u],
];
for (const [relativePath, pattern] of positioningChecks) {
  const text = await readFile(path.join(root, relativePath), 'utf8');
  if (!pattern.test(text)) failures.push(`current product positioning missing from ${relativePath}`);
}

if (failures.length) {
  console.error('RELEASE_AUDIT_FAILED');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log(`RELEASE_AUDIT_OK ${files.length} files version=${packageVersion}`);
