import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = path.resolve(process.cwd());
const ignoredDirectories = new Set([
  '.git',
]);
const forbiddenRepositorySegments = new Set([
  'node_modules',
  'dist',
  'target',
  'gen',
  '__pycache__',
  'vault',
  '.obsidian',
  'coverage',
  'test-results',
  'screenshots',
  'design-qa',
  'runtime',
  'logs',
  'checkpoints',
  'backups',
  'cache',
]);
const binaryExtensions = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.ico', '.icns', '.pdf', '.zip', '.dmg', '.app',
]);
const requiredFiles = [
  'README.md',
  'ARCHITECTURE.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
  'CHANGELOG.md',
  'LICENSE',
  'NOTICE',
  'package.json',
  'package-lock.json',
  'desktop-ui/index.html',
  'desktop-ui/app.js',
  'desktop-ui/styles.css',
  'src-tauri/Cargo.toml',
  'src-tauri/Cargo.lock',
  'src-tauri/tauri.conf.json',
  'src-tauri/src/lib.rs',
  'src-tauri/src/command_bus.rs',
  'src-tauri/src/policy.rs',
  'src-tauri/src/task_runtime.rs',
  'src-tauri/src/obsidian.rs',
  'src-tauri/src/obsidian_management.rs',
  'src-tauri/src/runtime_db.rs',
  'docs/assets/architecture-overview.svg',
  '.github/workflows/ci.yml',
  '.github/workflows/windows-installer.yml',
  '.github/ISSUE_TEMPLATE/bug_report.yml',
  '.github/ISSUE_TEMPLATE/feature_request.yml',
  'scripts/build-windows-media-helper.mjs',
  'scripts/build-windows-native.mjs',
  'scripts/build-windows-python-runtime.mjs',
  'scripts/quality-gates.mjs',
  'scripts/verify-windows-release.mjs',
  'skills/document-content-analysis/scripts/yunspire_image_windows.cpp',
  'skills/document-content-analysis/scripts/yunspire_pdf_windows.cpp',
  'skills/video-content-analysis/scripts/yunspire_media_windows.cpp',
  'skills/video-content-analysis/scripts/yunspire_speech_windows.cpp',
  'src-tauri/tauri.windows.conf.json',
];
const bilingualDocuments = [
  'README.md',
  'ARCHITECTURE.md',
  'CONTRIBUTING.md',
  'SECURITY.md',
  'CHANGELOG.md',
  'docs/AI_ASSISTANT_INSTRUCTIONS.md',
  'docs/BRAND_GUIDE.md',
  'docs/PRODUCT_REQUIREMENTS.md',
  'docs/schemas/README.md',
];
const generatedAttributionPattern = new RegExp(
  `(?:generated by|co-authored-by:).*(?:${['Chat', 'GPT'].join('')}|${['Co', 'dex'].join('')}|${['Clau', 'de'].join('')})`,
  'gi',
);
const forbiddenPatterns = [
  { label: 'macOS absolute user path', pattern: /\/Users\/[^/\s"'`<>]+\//g },
  { label: 'Linux absolute user path', pattern: /\/home\/[^/\s"'`<>]+\//g },
  { label: 'Windows absolute user path', pattern: /[A-Za-z]:\\Users\\[^\\\s"'`<>]+\\/g },
  { label: 'local file URL', pattern: /file:\/\/(?:\/|[A-Za-z]:)/g },
  { label: 'private key', pattern: /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/g },
  { label: 'AWS access key', pattern: /\bAKIA[0-9A-Z]{16}\b/g },
  { label: 'OpenAI-style secret', pattern: /\bsk-[A-Za-z0-9_-]{20,}\b/g },
  { label: 'generated authorship marker', pattern: generatedAttributionPattern },
];

async function exists(relativePath) {
  try {
    await stat(path.join(root, relativePath));
    return true;
  } catch {
    return false;
  }
}

async function collectFiles(directory, relative = '') {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const nextRelative = path.join(relative, entry.name);
    if (entry.isDirectory()) {
      if (ignoredDirectories.has(entry.name)) continue;
      if (forbiddenRepositorySegments.has(entry.name)) {
        failures.push(`generated or local artifact present: ${nextRelative}${path.sep}`);
        continue;
      }
      files.push(...await collectFiles(path.join(directory, entry.name), nextRelative));
    } else if (entry.isSymbolicLink()) {
      failures.push(`symbolic link is not allowed in release source: ${nextRelative}`);
    } else if (entry.isFile()) {
      files.push(nextRelative);
    }
  }
  return files;
}

const failures = [];
for (const required of requiredFiles) {
  if (!await exists(required)) failures.push(`missing required file: ${required}`);
}

for (const document of bilingualDocuments) {
  if (!await exists(document)) continue;
  const text = await readFile(path.join(root, document), 'utf8');
  if (!/^## 中文$/m.test(text) || !/^## English$/m.test(text)) {
    failures.push(`bilingual headings missing: ${document}`);
  }
}

const files = await collectFiles(root);
for (const relativePath of files) {
  const segments = relativePath.split(path.sep);
  if (segments.some((segment) => forbiddenRepositorySegments.has(segment))) {
    failures.push(`generated or local artifact present: ${relativePath}`);
    continue;
  }
  if (binaryExtensions.has(path.extname(relativePath).toLowerCase())) continue;
  const fileStat = await stat(path.join(root, relativePath));
  if (fileStat.size > 5 * 1024 * 1024) continue;
  const text = await readFile(path.join(root, relativePath), 'utf8');
  for (const { label, pattern } of forbiddenPatterns) {
    pattern.lastIndex = 0;
    if (pattern.test(text)) failures.push(`${label}: ${relativePath}`);
  }
}

const packageJson = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
const packageVersion = packageJson.version;
const versionChecks = [
  ['src-tauri/tauri.conf.json', new RegExp(`"version"\\s*:\\s*"${packageVersion.replaceAll('.', '\\.')}"`)],
  ['src-tauri/Cargo.toml', new RegExp(`^version\\s*=\\s*"${packageVersion.replaceAll('.', '\\.')}"`, 'm')],
  ['desktop-ui/index.html', new RegExp(`版本 ${packageVersion.replaceAll('.', '\\.')}`)],
  ['desktop-ui/app.js', new RegExp(`Yunspire Desktop ${packageVersion.replaceAll('.', '\\.')}`)],
  ['skills/video-content-analysis/scripts/yunspire_speech_info.plist', new RegExp(`<string>${packageVersion.replaceAll('.', '\\.')}<\\/string>`)],
];
for (const [relativePath, pattern] of versionChecks) {
  const text = await readFile(path.join(root, relativePath), 'utf8');
  if (!pattern.test(text)) failures.push(`version mismatch in ${relativePath}; expected ${packageVersion}`);
}

if (failures.length) {
  console.error('RELEASE_AUDIT_FAILED');
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

console.log(`RELEASE_AUDIT_OK ${files.length} files version=${packageVersion}`);
